version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./MovieDatabase:/MovieDatabase
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=moviedatabase
      - DB_USER=manager
      - DB_PASS=password1!

    depends_on:
        - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=moviedatabase
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=password1!